# Generated by Django 5.1.7 on 2025-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="group_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
