# Generated by Django 5.1.7 on 2025-03-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_group_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
    ]
