# Generated by Django 5.1.7 on 2025-03-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_participants",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
