# Generated by Django 5.1.7 on 2025-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_min_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_participants",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
