# Generated by Django 5.1.7 on 2025-03-24 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_max_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
