# Generated by Django 5.1.7 on 2025-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_cartitem_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="products.category"),
        ),
    ]
