# Generated by Django 5.1.7 on 2025-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_category_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Makeup", "Makeup"),
                    ("Perfumes", "Perfumes"),
                    ("Brands", "Brands"),
                    ("Skincare", "Skincare "),
                    ("Haircare", "Haircare"),
                    ("Electronics", "Electronics"),
                ],
                default=2,
                max_length=250,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
