# Generated by Django 5.1.7 on 2025-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_product_brand_delete_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Makeup", "Makeup"),
                    ("Perfumes", "Perfumes"),
                    ("Skincare", "Skincare "),
                    ("Haircare", "Haircare"),
                    ("Electronics", "Electronics"),
                ],
                max_length=250,
            ),
        ),
    ]
