# Generated by Django 5.1.7 on 2025-04-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_brand_alter_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
