# Generated by Django 5.1.7 on 2025-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_profile_user_about_remove_profile_user_avatar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile_user",
            name="avatar",
            field=models.ImageField(
                default="images/avatars/avatar.webp", upload_to="images/avatars/"
            ),
        ),
    ]
