# Generated by Django 5.1.7 on 2025-03-23 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppurchase",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
