# Generated by Django 5.1.7 on 2025-03-24 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_grouppurchase_participants_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppurchase",
            name="participants",
        ),
        migrations.AddField(
            model_name="grouppurchase",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="group_purchases", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
