# Generated by Django 5.1.7 on 2025-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_grouppurchase_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppurchase",
            name="expiration_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
