# Generated by Django 5.1.7 on 2025-04-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_grouppurchase_expiration_time_paymenttest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppurchase",
            name="expiration_time",
        ),
    ]
