# Generated by Django 5.1.7 on 2025-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_remove_grouppurchase_expiration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppurchase",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
